[SeqrMTToESTask]
# Passed to SeqrVCFToMTTask.
reference_ht_path = "abfss://reference@azcpg001sa.dfs.core.windows.net/seqr/v0-1/combined_reference_data_grch38.ht"
clinvar_ht_path = "abfss://reference@azcpg001sa.dfs.core.windows.net/seqr/v0-1/clinvar.GRCh38.ht"
grch38_to_grch37_ref_chain = "abfss://reference@azcpg001sa.dfs.core.windows.net/hail/grch38_to_grch37.over.chain.gz"
vep_config_json_path = "/vep_configs/vep-GRCh38-loftee.json"
genome_version = "38"

[GlobalConfig]
validation_38_coding_ht = "abfss://reference@azcpg001sa.dfs.core.windows.net/seqr/v0-1/validate_ht/common_coding_variants.grch38.ht"
validation_38_noncoding_ht = "abfss://reference@azcpg001sa.dfs.core.windows.net/seqr/v0-1/validate_ht/common_noncoding_variants.grch38.ht"
